############################################
# The Tmux prefix

# The default Tmux prefix, `C-b` is not acceptable -- Vim uses it
# Use `C-z` as the prefix key, it's near the home row and not used by Vim
# `C-z` normally backgrounds the current process, which I have no need for.
set-option -g prefix C-z

############################################
# Key Bindings

# List current bindings:
# $ tmux list-keys

# Acceptable values are listed in man page 'KEY BINDINGS'

# prefix + `-` jumps to previous window
bind - select-window -l
# prefix + prefix jumps to previous window
bind-key C-z select-window -l
# Possible alternatives:
# Disable prefix + prefix
# unbind-key C-z
# Send `C-z` after prefix + `C-z` (i.e. `C-z C-z`) to background the current process
# bind-key C-z send-prefix

# Sometimes, I'm slow to release the Ctrl key.
# Normally prefix + `c` creates a new window, allow prefix + `C-c`
bind C-c new-window

# prefix + `r` = reload config
bind r source-file ~/.tmux.conf \; display-message "Tmux config reloaded..."

# I often accidentally hit prefix + `m` which selects the "marked pane", which is a functionality
# I don't use. More annoyingly, it puts an 'M' next to the pane, which is distracting. Unbind it.
unbind-key m

# Reduce timeout on Esc that slows Neovim
set -sg escape-time 10

############################################
# Copy Mode

# Copy mode allows navigating in the history of text in a pane and optionally copying text.
# Enter copy mode: prefix + `[`

# Use Vim keybindings to navigate and select text
set-window-option -g mode-keys vi

# Copy selection: Enter

############################################
# History

set-option -g history-limit 10000

#############################################
# Status line

# Set a background similar to nvim's background
set -g status-bg colour235
set -g status-fg white
set -g status-left ""
set -g status-right "#(cd #{pane_current_path}; $HOME/bin/jgy-tmux-git-status) #[fg=yellow]#(date +%H:%M)"

# Highlight active window
set-window-option -g window-status-current-style bg=blue
